### ISSUE TITLE
通讯录建议

### ISSUE THREAD

**Issue by ackdiff** [zju-cst-fellow/zju-cst-fellow#6]
校园邮箱一般毕业后就会被注销掉，当然回头改也行，但可能会忘了，所以建议使用私人邮箱。公司邮箱同理。这样的话，一般可以保证学弟学妹看到信息一直是可用的。

**Comment by shenxs** [comment]
联系方式是出于自愿和保护个人隐私的原则上传的。
但是长期有效性确实一个问题，如果分享者愿意的话可以放上私人邮箱。

**Comment by daixinye** [comment]
好像确实会注销，如果愿意的话建议私人邮箱吧，后续我会在 README 里改一下相关文案

**Comment by daixinye** [comment]
我和 @shenxs @Alexzsh 两位小伙伴讨论了一下，最终觉得放一个「公司邮箱」或「任何长期有效的联系方式」，包括且不限于私人邮箱、微信号、手机号等都可以。
